[theme]
# Primary accent color for interactive elements.
#primaryColor = "#E694FF"

# Background color for the main content area.
#backgroundColor = "#00172B"

# Background color used for the sidebar and most interactive widgets.
#secondaryBackgroundColor = "#0083B8"

# Color used for almost all text.
#textColor = "#FFF"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
#font = "sans serif"

#[theme]
#primaryColor = "#eb4034"
#backgroundColor = "#021d24"
#secondaryBackgroundColor = "#25B1B5"
#textColor = "#FFF"
#font = "sans serif"

primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"